# Generated by Django 5.2.7 on 2025-10-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('NATURAL', 'Natural'), ('SOCIAL', 'Social'), ('POLITICAL', 'Political')], default='SOCIAL', max_length=10)),
            ],
        ),
    ]
