# Generated by Django 5.2.7 on 2025-10-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post'),
            preserve_default=False,
        ),
    ]
